In [1]:
import numpy as n
arr=n.array([1,2,45,12,23,3,4,45,34,121,3,3,45])
temp=n.where(arr==3)
print(temp)

(array([ 5, 10, 11], dtype=int64),)


In [3]:
temp1=n.where(arr%2==0)
print(temp1)

(array([1, 3, 6, 8], dtype=int64),)


In [4]:
x=n.sort(arr)
print(x)

[  1   2   3   3   3   4  12  23  34  45  45  45 121]


In [5]:
y=n.searchsorted(x,6)
print(y)

6


In [8]:
z=n.array([[1,4,5,2],[12,4,5,2]])
x1=[True,False,True,False,True,False,True,False,True,False,True,False,True]
new=x[x1]
print(new)


[  1   3   3  12  34  45 121]


In [9]:
arr21=n.array([1,2,3,4])
x_2=arr21>3
print(arr21[x-2])

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (3579900750.py, line 2)