In [2]:
import numpy as np 
a=np.array([[1,2,3,4],[5,6,7,8],[0,2,4,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [0 2 4 8]]


In [3]:
b=np.zeros((1,4,3))
print(b) 

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
d=np.random.random((4,3))
print(d)

[[0.18075439 0.87401942 0.77066422]
 [0.0221673  0.92303016 0.69272564]
 [0.47121699 0.8045072  0.39755447]
 [0.70123345 0.52609648 0.61254204]]


In [7]:
c=np.full((4,3),3)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [11]:
e=np.arange(3,36,5)
print(e)

[ 3  8 13 18 23 28 33]


In [12]:
print(c.reshape(3,4))


[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [15]:
print(c.flatten())

[3 3 3 3 3 3 3 3 3 3 3 3]


In [16]:
print(c.ndim)


2
