In [2]:
import numpy as np 
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a)

[[1 2 3 4]
 [2 3 4 5]]


In [3]:
print(a[1:3:2])

[[2 3 4 5]]


In [4]:
print(a[1:3:1])

[[2 3 4 5]]


In [5]:
print(a[:2,:3])

[[1 2 3]
 [2 3 4]]


In [7]:
code=a>2
print(a[code])

[3 4 3 4 5]


In [8]:
print(a[a>=5])

[5]


In [9]:
print(a[::2])

[[1 2 3 4]]


In [10]:
print(a[1::])

[[2 3 4 5]]


In [11]:
print(a[:2:])

[[1 2 3 4]
 [2 3 4 5]]


In [13]:
a1=np.array([6,7])
a2=np.array([2,3])
arr=np.concatenate((a2,a1))
print(arr)

[2 3 6 7]
