In [4]:
import numpy as np
arr1=np.array([1,23,23,12,15])
arr2=np.array([13,12,34,67,56])
print(arr1,"\n",arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)

[ 1 23 23 12 15] 
 [13 12 34 67 56]
[14 35 57 79 71]
[-12  11 -11 -55 -41]
[0.07692308 1.91666667 0.67647059 0.17910448 0.26785714]


In [4]:
import numpy as np
def fun(x,y):
   if x>y:
       return x-y
   else:
       return x+y
arr1=[1,2,3]
arr2=[4,5,6]
vec_func=np.vectorize(fun)
print(vec_func(arr1,arr2))
   


[5 7 9]


In [5]:
sclr=5
print(sclr*arr1)
   

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
